//+------------------------------------------------------------------+
//|                                                VolatilityEA.mq4  |
//|                                       Generated by ChatGPT       |
//+------------------------------------------------------------------+
#property strict
#property description "Bollinger+RSI+ADX strategy with pyramiding"

//--- input parameters
input int    MagicNumber      = 123456;   // Magic number
input double RiskPercent      = 2.0;      // Percent of balance per trade
input double MaxBBWidthPct    = 2.0;      // Bollinger band width threshold
input int    CalmPeriodBars   = 24;       // Cooling off bars
input double Slippage         = 0.01;     // Slippage allowed

//--- constants
#define MAX_LAYERS 4

//--- globals
int    ConsecutiveLosses=0;
bool   InCalm=false;
datetime CalmStart=0;
datetime LastBarTime=0;

//+------------------------------------------------------------------+
//| Calculate lot size based on balance and risk percent             |
//+------------------------------------------------------------------+
double GetLotSize()
{
   double lotStep   = MarketInfo(Symbol(), MODE_LOTSTEP);
   double minLot    = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot    = MarketInfo(Symbol(), MODE_MAXLOT);
   double lot       = AccountBalance()*RiskPercent/100.0/MarketInfo(Symbol(), MODE_MARGINREQUIRED);
   lot = MathMax(minLot, MathMin(maxLot, lot));
   lot = MathFloor(lot/lotStep)*lotStep;
   return NormalizeDouble(lot,2);
}

//+------------------------------------------------------------------+
//| Get ATR(20)                                                      |
//+------------------------------------------------------------------+
double GetN(int shift=0)
{
   return iATR(Symbol(),0,20,shift);
}

//+------------------------------------------------------------------+
//| Count orders by type and magic                                   |
//+------------------------------------------------------------------+
int CountOrders(int op)
{
   int total=0;
   for(int i=0;i<OrdersTotal();i++)
   {
      if(OrderSelect(i,SELECT_BY_POS,MODE_TRADES))
      {
         if(OrderMagicNumber()==MagicNumber && OrderSymbol()==Symbol() && OrderType()==op)
            total++;
      }
   }
   return total;
}

//+------------------------------------------------------------------+
//| Return highest open price among buy orders                       |
//+------------------------------------------------------------------+
double HighestBuyPrice()
{
   double price=0;
   for(int i=0;i<OrdersTotal();i++)
   {
      if(OrderSelect(i,SELECT_BY_POS,MODE_TRADES))
      {
         if(OrderMagicNumber()==MagicNumber && OrderSymbol()==Symbol() && OrderType()==OP_BUY)
            price=MathMax(price,OrderOpenPrice());
      }
   }
   return price;
}

//+------------------------------------------------------------------+
//| Return lowest open price among sell orders                       |
//+------------------------------------------------------------------+
double LowestSellPrice()
{
   double price=0;
   bool first=true;
   for(int i=0;i<OrdersTotal();i++)
   {
      if(OrderSelect(i,SELECT_BY_POS,MODE_TRADES))
      {
         if(OrderMagicNumber()==MagicNumber && OrderSymbol()==Symbol() && OrderType()==OP_SELL)
         {
            if(first){ price=OrderOpenPrice(); first=false; }
            price=MathMin(price,OrderOpenPrice());
         }
      }
   }
   return price;
}

//+------------------------------------------------------------------+
//| Manage trailing stops                                            |
//+------------------------------------------------------------------+
void ManageTrailingStops()
{
   if(Time[0]==LastBarTime) return; // update once per bar
   LastBarTime=Time[0];

   double N=GetN();
   for(int i=0;i<OrdersTotal();i++)
   {
      if(OrderSelect(i,SELECT_BY_POS,MODE_TRADES))
      {
         if(OrderMagicNumber()!=MagicNumber || OrderSymbol()!=Symbol()) continue;
         double openPrice=OrderOpenPrice();
         double stop=OrderStopLoss();
         double profitPoints = (OrderType()==OP_BUY) ? Bid-openPrice : openPrice-Ask;
         double profitN = profitPoints/N;
         double newStop=stop;
         if(profitN>6)
         {
            if(OrderType()==OP_BUY)
               newStop= MathMax(stop, Bid-0.5*N);
            else
               newStop= MathMin(stop, Ask+0.5*N);
         }
         else if(profitN>4)
         {
            if(OrderType()==OP_BUY)
               newStop= MathMax(stop, Bid-1.5*N);
            else
               newStop= MathMin(stop, Ask+1.5*N);
         }
         if(MathAbs(newStop-stop)>Point)
            OrderModify(OrderTicket(),OrderOpenPrice(),newStop,OrderTakeProfit(),0,CLR_NONE);
      }
   }
}

//+------------------------------------------------------------------+
//| Open a new order                                                 |
//+------------------------------------------------------------------+
void OpenOrder(int op)
{
   double N = GetN();
   double price = (op==OP_BUY) ? Ask : Bid;
   double sl = (op==OP_BUY) ? price-2*N : price+2*N;
   double lot=GetLotSize();
   int ticket=OrderSend(Symbol(),op,lot,price,Slippage*10,sl,0,"EA",MagicNumber,0,clrBlue);
}

//+------------------------------------------------------------------+
//| Check entry signals                                              |
//+------------------------------------------------------------------+
void CheckSignals()
{
   if(InCalm) return;
   double upper=iBands(Symbol(),0,20,2,0,PRICE_CLOSE,MODE_UPPER,0);
   double lower=iBands(Symbol(),0,20,2,0,PRICE_CLOSE,MODE_LOWER,0);
   double middle=iBands(Symbol(),0,20,2,0,PRICE_CLOSE,MODE_MAIN,0);
   double width=(upper-lower)/middle*100.0;
   double adx=iADX(Symbol(),0,14,PRICE_CLOSE,MODE_MAIN,0);

   int buyCount=CountOrders(OP_BUY);
   int sellCount=CountOrders(OP_SELL);

   if(Bid>=upper && width<MaxBBWidthPct && adx>25 && adx<40)
   {
      if(buyCount<MAX_LAYERS)
      {
         double lastPrice=HighestBuyPrice();
         double N=GetN();
         if(buyCount==0 || Bid-lastPrice>=0.5*N)
            OpenOrder(OP_BUY);
      }
   }
   else if(Ask<=lower && width<MaxBBWidthPct && adx>25 && adx<40)
   {
      if(sellCount<MAX_LAYERS)
      {
         double lastPrice=LowestSellPrice();
         double N=GetN();
         if(sellCount==0 || lastPrice-Ask>=0.5*N)
            OpenOrder(OP_SELL);
      }
   }
}

//+------------------------------------------------------------------+
//| Check for closed orders to manage calm period                    |
//+------------------------------------------------------------------+
void CheckClosedTrades()
{
   static int historyTotal=0;
   int total=OrdersHistoryTotal();
   for(int i=historyTotal;i<total;i++)
   {
      if(OrderSelect(i,SELECT_BY_POS,MODE_HISTORY))
      {
         if(OrderMagicNumber()==MagicNumber && OrderSymbol()==Symbol())
         {
            if(OrderProfit()<0) ConsecutiveLosses++; else ConsecutiveLosses=0;
            if(ConsecutiveLosses>=2)
            {
               InCalm=true;
               CalmStart=Time[0];
            }
         }
      }
   }
   historyTotal=total;

   if(InCalm && (Time[0]-CalmStart>=CalmPeriodBars*Period()))
   {
      InCalm=false;
      ConsecutiveLosses=0;
   }
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   ManageTrailingStops();
   CheckSignals();
   CheckClosedTrades();
}

//+------------------------------------------------------------------+
//| End of file                                                      |
//+------------------------------------------------------------------+
